### ISSUE TITLE
[Enhancement] Routing for 'Intro to pandas'

### ISSUE THREAD

**Issue by fjuren** [thecuriousteam/PyLibLog#100]
Selecting 'Intro to pandas' shows no routes available. I can take a look at this, please assign me.

![image](https://github.com/thecuriousteam/PyLibLog/assets/65582950/c24aefba-882c-4906-b8b8-e639e9231bee)

**Comment by thecuriousteam** [comment]
Yes You can work on it @fjuren

**Comment by Sravaani** [comment]
Resolved routing issue "intro to pandas"

**Comment by Sravaani** [comment]
@fjuren yeah, its done.
