### ISSUE TITLE
Add a user Friendly Home Page

### ISSUE THREAD

**Issue by PlanetKumbhaj** [thecuriousteam/PyLibLog#11]
here you need to add Home page frontend . with relevant  tech stack .

**Comment by shweta-kush** [comment]
hello sir, please assign this task to me. i would like to contribute

**Comment by thecuriousteam** [comment]
Ok, You can start contributing.
Meanwhile, I will request you to join the [community ](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7) and claim the contribution certificate once 3 issues has been resolved by you .

**Comment by 457ayan** [comment]
Please assign to me this project

**Comment by thecuriousteam** [comment]
yes , You can start working on the project .

**Comment by thecuriousteam** [comment]
Guys please maintain the design principles which is standard
@shweta-kush @457ayan
