### ISSUE TITLE
Add a favicon 

### ISSUE THREAD

**Issue by ayush-agarwal-190** [thecuriousteam/PyLibLog#151]
Their is a folder called logo and assert, please take reference from it and add a favicon.

**Comment by thecuriousteam** [comment]
Yes You Can Work On it @chiku011 

Thank You

## Instructions

1. Yes you can start working on it by taking latest pull from main branch
2. Don't Forget to join onboarding group for knowledge flow and direct conversation and support from other developers link  [Curious Developers Community - Hacktoberfest ](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)
3. Please attach the screenshots and video of the development work once it is done
4. Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem please mail to (admin@curiousdevelopers.in) for claiming certificate and please attach your issue number 
5. Respect Co Developers And Please Reachout to admins if any issues

**Comment by shoaib-31** [comment]
@thecuriousteam Can you assign it to me? I don't think adding a favicon takes 18 hours.
