### ISSUE TITLE
Throwing 404 on deployment , after refreshing the page link in the comment 

### ISSUE THREAD

**Issue by thecuriousteam** [thecuriousteam/PyLibLog#178]
https://pyliblog.curiousdevelopers.in/play-ground

**Comment by thecuriousteam** [comment]
@Chetan-Jalandharia we are doing in hostinger the manual deployment, going forward we will use jenkins and AWS/GCP

@Chetan-Jalandharia are you part of CDC on boarding group for hacktoberfest?

**Comment by samrat2k03** [comment]
mate, i think there is no problem in code, you need fix the issue by Updating your server configuration based on the web server running.
