### ISSUE TITLE
Add content to seaborn

### ISSUE THREAD

**Issue by ayush-agarwal-190** [thecuriousteam/PyLibLog#191]

**Comment by antoash** [comment]
Hey, can you assign this to me?

**Comment by ayush-agarwal-190** [comment]
Ok, you can start working on it.

**Comment by antoash** [comment]
Should I create a new folder in assets for the images of plots?

**Comment by thecuriousteam** [comment]
Yes Please create inside the Seaborn Folder

Thank You

## Instructions

1. Yes you can start working on it by taking latest pull from main branch
2. Don't Forget to join onboarding group for knowledge flow and direct conversation and support from other developers link  [Curious Developers Community - Hacktoberfest ](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)
3. Please attach the screenshots and video of the development work once it is done
4. Contributions more than 3 will be awarded a certificate of appreciation from curious ecosystem please mail to (admin@curiousdevelopers.in) for claiming certificate and please attach your issue number 
5. Respect Co Developers And Please Reachout to admins if any issues
