### ISSUE TITLE
[Bug] console log error on search

### ISSUE THREAD

**Issue by fjuren** [thecuriousteam/PyLibLog#99]
When entering content to the search bar, console flags an error. Happy to take a look at this, please assign me.

![image](https://github.com/thecuriousteam/PyLibLog/assets/65582950/6e6b15b8-0dd5-413d-b451-bac614c2bdd9)

**Comment by thecuriousteam** [comment]
Yes You can work on it @fjuren, please join our onboarding group

Developers needs to onboard to opensource community for easy information flow along with admins, please join with this link  [Curious Developers Community - Hacktoberfest ](https://chat.whatsapp.com/HNu3VaLPK3z3yt3JFUs7D7)</br>

**Comment by Sravaani** [comment]
Use index as a key in order to avoid the bug !
